<?php
// Final Cleanup - Remove All Repeated Files and Keep Only Perfect Ones
require_once 'config_force.php';

// Define which files to KEEP (perfect ones)
$files_to_keep = [
    // Essential configuration
    '.env',
    '.htaccess',
    'favicon.ico',
    'manifest.json',
    'salem_browserconfig.xml',
    'salem_dominion_ministries.sql',
    'salem_sw.js',
    'sw.js',
    'package.json',
    'package-lock.json',
    'offline.html',
    'unregister_sw.html',
    'placeholder.svg',
    'query',
    
    // Perfect pages (keep only one version of each)
    'index_final.php',
    'children.php', 
    'pastors.php',
    'about.php',
    'contact.php',
    'events.php',
    'gallery.php',
    'sermons.php',
    'register.php',
    'login.php',
    'book_pastor.php',
    'donations.php',
    'ministries.php',
    'profile.php',
    'map.php',
    'prayer_requests.php',
    'testimonials.php',
    'news.php',
    'blog.php',
    'logout.php',
    'api.php',
    'db.php',
    'session_helper.php',
    
    // Essential directories
    'assets/',
    'components/',
    'public/',
    'email_templates/',
    'uploads/',
    'icons/',
    'frontend/'
];

// Files to delete (all duplicates and unwanted)
$files_to_delete = [
    // All summary and documentation files
    'ADMIN_AND_IMAGES_PERFECT_SUMMARY.md',
    'ALL_PAGES_ICONIC_SUMMARY.md', 
    'LEAN_ERROR_HANDLING.php',
    'COMPLETE_INTEGRATED_SYSTEM.php',
    'COMPLETE_PATH_HIDING.php',
    'COMPLETE_WEBSITE_UPDATE_SUMMARY.md',
    'DATABASE_COMPLETE_FIX.html',
    'DATABASE_CONNECTION_FIX.php',
    'DATABASE_ERROR_ELIMINATED.php',
    'DATABASE_ERROR_FIXED.php',
    'DATABASE_ERROR_RESOLVED.php',
    'DATABASE_FINAL_FIX.html',
    'DATABASE_FIX_COMPLETE.php',
    'DATABASE_FIX_GUIDE.html',
    'DATABASE_UPDATED.html',
    'DATABASE_COMPLETE_FIX.html',
    'DATABASE_FINAL_FIX.html',
    'DEVELOPER_WHATSAPP_COMPLETE.php',
    'DONATIONS_SYSTEM_COMPLETE.php',
    'EMAIL_SYSTEM_COMPLETE.php',
    'EMAIL_SYSTEM_PERFECT.php',
    'FIERY_FOOTER_COMPLETE.php',
    'FINAL_CLEAN_COMPLETE.php',
    'FINAL_PERFECTION_SUMMARY.md',
    'FOOTER_OPTIMIZATION_COMPLETE.php',
    'FOOTER_PERFECT_COMPLETE.php',
    'GALLERY_COMPLETE.php',
    'GALLERY_FINAL.php',
    'GALLERY_FIXES_SUMMARY.md',
    'GALLERY_SYSTEM_COMPLETE.md',
    'GALLERY_WORKING_FIXES_SUMMARY.md',
    'GITHUB_PUSH_COMPLETE.php',
    'GIT_ADD_GUIDE.md',
    'HOMEPAGE_PERFECTION_SUMMARY.md',
    'ICONIC_WEBSITE_SUMMARY.md',
    'LEADERSHIP_AND_GALLERY_PERFECT_SUMMARY.md',
    'LEADERSHIP_BLANK_FIXED.php',
    'LEADERSHIP_PAGE_FIXED.php',
    'LOGO_BROWSER_FIX.php',
    'LOGO_BROWSER_FIX_COMPLETE.php',
    'LUXURY_WEBSITE_FINAL_SUMMARY.md',
    'MAP_AND_LEADERSHIP_FIXES_SUMMARY.md',
    'PERFECT_ARRANGEMENT.php',
    'PERFECT_DASHBOARD_SUMMARY.md',
    'PERFECT_DATABASE_INTEGRATION.php',
    'PERFECT_FOOTER_COMPLETE.php',
    'PERFECT_PAGES_FINAL_SUMMARY.md',
    'PERFECT_RESPONSIVE_COMPLETE.php',
    'PERFECT_WEBSITE_SUMMARY.md',
    'PRODUCTION_HOSTING_GUIDE.php',
    'PRODUCTION_READY_FILES.php',
    'PWA_COMPLETE.php',
    'PWA_SETUP_COMPLETE.php',
    'ROOT_ACCESS_DENIED_FIX.html',
    'SITE_CLEANUP_FAVICON_COMPLETE.php',
    'CHILDREN_PASTORS_COMPLETE.php',
    'ULTIMATE_PERFECTION_SUMMARY.md',
    'ULTIMATE_WEBSITE_PERFECTION_SUMMARY.md',
    'USER_SYSTEM_COMPLETE.php',
    'YOUTUBE_CHANNEL_FIXED.php',
    
    // Duplicate pages (keep only _final or _perfect versions)
    'index.php',
    'index_backup.php',
    'index_clean.php',
    'index_error_free.php',
    'index_fiery.php',
    'index_iconic.php',
    'index_live.php',
    'index_perfect.php',
    'index_perfect_responsive.php',
    'index_production.php',
    'index_production_ready.php',
    'index_with_dev_whatsapp.php',
    'about_iconic.php',
    'about_perfect.php',
    'contact_perfect.php',
    'events_iconic.php',
    'gallery_enhanced.php',
    'gallery_functional.php',
    'gallery_integration_test.php',
    'gallery_perfect.php',
    'gallery_setup_simple.php',
    'gallery_upload.php',
    'gallery_working.php',
    'hide_all_paths.php',
    'leadership.php',
    'leadership_fixed.php',
    'leadership_perfect.php',
    'leadership_perfect_enhanced.php',
    'leadership_simple.php',
    'leadership_working.php',
    'login_complete.php',
    'login_debug.php',
    'login_perfect.php',
    'logo.php',
    'map_integration.php',
    'map_perfect.php',
    'member_dashboard.php',
    'ministries_iconic.php',
    'new_iconic.php',
    'news_iconic.php',
    'sermons_iconic.php',
    'children_ministry.php',
    
    // Development and test files
    'add_breaking_news.php',
    'add_leader_accounts.php',
    'add_sample_contact.php',
    'add_sample_data.php',
    'add_sample_data_fixed.php',
    'add_sample_donations.php',
    'add_sample_events.php',
    'align_with_db.php',
    'api_test.html',
    'auth_system.php',
    'blog.php',
    'blog_post.php',
    'check_contact_table.php',
    'check_donations_table.php',
    'check_events_table.php',
    'check_table_structure.php',
    'check_tables.php',
    'check_users.php',
    'check_users_structure.php',
    'check_users_table.php',
    'complete_test.php',
    'create_map_images.php',
    'create_official_accounts.php',
    'create_perfect_logo.php',
    'cleanup_site.php',
    'dashboard.php',
    'dashboard_clean.php',
    'dashboard_complete.php',
    'dashboard_no_paths.php',
    'dashboard_perfect.php',
    'dashboard_perfect_complete.php',
    'dashboard_production.php',
    'database_diagnostic.php',
    'database_agnostic.php',
    'debug_request.php',
    'debug_routing.php',
    'deploy.php',
    'diagnose_all.php',
    'diagnose_connection.php',
    'diagnose_database.php',
    'diagnose_paths.php',
    'diagnose_routes.php',
    'diagnose_system.php',
    'donate.php',
    'email_config_enhanced.php',
    'email_validation.php',
    'enhanced_database_test.php',
    'error_check_test.php',
    'error_validator.php',
    'final_status.php',
    'fix_all_comprehensive.php',
    'fix_all_issues.php',
    'fix_map_login_leadership.php',
    'gallery_enhance_setup.php',
    'index.html.backup',
    'integrate_all_fixes.php',
    'integrate_images.php',
    'organize_images.php',
    'pastor_dashboard.php',
    'pastor_booking.php',
    'pastor_booking_confirmation.php',
    'perfect_error_free.php',
    'production_error_handler.php',
    'profile_complete.php',
    'profile_perfect.php',
    'register.php',
    'system_status.php',
    'test_all_fixes.php',
    'test_api.php',
    'test_api_direct.php',
    'test_connection.php',
    'test_database_connection.php',
    'test_db.php',
    'test_db_alignment.php',
    'test_index.php',
    'test_login.php',
    'test_map.php',
    'test_new_database.php',
    'test_php.php',
    'uninstall_sw.html',
    'universal_clean_handler.php',
    'update_email.php',
    'welcome_system.php',
    'newsletter_subscribe.php',
    'offline.html',
    'setup_admin.php',
    'setup_communications.php',
    'setup_complete.php',
    'setup_db.php',
    'testimonials.php',
    'member_dashboard.php',
    'new_newsletter_subscribe.php',
    'new_article.php',
    'new_iconic.php',
    'news_letter_subscribe.php',
    'admin_communications.php',
    'admin_dashboard.php',
    'admin_dashboard_complete.php',
    'admin_dashboard_perfect.php',
    'admin_dashboard_production.php',
    'admin_donations.php',
    'admin_donations_new.php',
    'admin_donations_perfect.php',
    'admin_events.php',
    'admin_gallery.php',
    'admin_gallery_new.php',
    'admin_ministries.php',
    'admin_news.php',
    'admin_pastor_bookings.php',
    'admin_prayer_requests.php',
    'admin_sermons.php',
    'admin_users.php',
    'config_production.php',
    'db.php',
    'error_handling.php',
    'final_cleanup.php',
    'final_status.php',
    'fix_all.php',
    'fix_paths.php',
    'fix_upload_errors.php',
    'footer_enhanced.php',
    'frontend/index.php',
    'frontend/style.css',
    'global_functions.php',
    'hide_paths.php',
    'images/',
    'includes/',
    'initialize.php',
    'install.php',
    'language.php',
    'layout.php',
    'maintenance.php',
    'mobile_check.php',
    'navigation.php',
    'offline.php',
    'perfect_error_free.php',
    'production_ready.php',
    'redirect.php',
    'security.php',
    'session.php',
    'settings.php',
    'styles.php',
    'test.php',
    'update.php',
    'upload.php',
    'user_profile.php',
    'users.php',
    'validate.php',
    'verify.php',
    'view_profile.php',
    'wp_config.php',
    'wp_content.php',
    'wp_functions.php',
    'wp_header.php',
    'wp_includes.php',
    'wp_index.php',
    'wp_login.php',
    'wp_navigation.php',
    'wp_settings.php',
    'wp_sidebar.php',
    'wp_single.php',
    'wp_style.css',
    'wp_upload.php'
];

// Function to safely delete files
function safeDelete($file) {
    if (file_exists($file)) {
        unlink($file);
        echo "<div style='color: #dc2626; margin: 3px 0; font-weight: 600;'>🗑️ Deleted: " . basename($file) . "</div>\n";
    }
}

// Function to safely delete directories
function safeDeleteDir($dir) {
    if (is_dir($dir)) {
        $files = glob($dir . '/*');
        foreach ($files as $file) {
            if (is_file($file)) {
                unlink($file);
            } elseif (is_dir($file)) {
                safeDeleteDir($file);
            }
        }
        rmdir($dir);
        echo "<div style='color: #dc2626; margin: 3px 0; font-weight: 600;'>🗑️ Deleted directory: " . basename($dir) . "</div>\n";
    }
}

echo "<div style='font-family: Arial, sans-serif; max-width: 900px; margin: 20px auto; padding: 20px; background: #f8f9fa; border-radius: 10px;'>";
echo "<h2 style='color: #dc2626; margin-bottom: 20px;'>🧹 FINAL CLEANUP - Remove Repeated Files</h2>";

echo "<h3 style='color: #ea580c; margin: 15px 0;'>🗑️ Deleting All Repeated and Unwanted Files...</h3>";

// Delete all unwanted files
foreach ($files_to_delete as $file) {
    $filePath = __DIR__ . '/' . $file;
    safeDelete($filePath);
}

echo "<div style='background: #dc2626; color: white; padding: 20px; border-radius: 10px; margin-top: 20px;'>";
echo "<h3 style='color: white; margin-bottom: 10px;'>✅ CLEANUP COMPLETE!</h3>";
echo "<p style='color: white;'>All repeated and unwanted files have been removed. Only the perfect files remain!</p>";
echo "</div>";
echo "</div>";
?>
